# Generated by Django 3.1.2 on 2020-10-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskfield', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
