# Generated by Django 3.1.2 on 2020-10-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '감정일기',
            },
        ),
    ]
